# Generated by Django 5.0.6 on 2024-07-04 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=datetime.date.today)),
                ('fecha_salida', models.CharField(max_length=200, unique=True)),
                ('cant_personas', models.IntegerField()),
            ],
            options={
                'db_table': 'Reserva',
            },
        ),
    ]
