# Generated by Django 5.0.6 on 2024-07-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ninetravel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(),
        ),
    ]
