version: '3.7'

services:

  web:
    image: httpd:latest
    container_name: website
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql_host
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reserva_db
    ports:
      - 3306:3306

  backend:
    build: ./Backend
    container_name: backend
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql